# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: local
  hooks:
  - id: nixpkgs-fmt
    name: nixpkgs-fmt
    language: script
    entry: pre-commit-hooks/nixpkgs-fmt
    types: [nix]
    pass_filenames: false
